# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

dist: focal

language: php

php:
  - 7.4
  - 8.0
  - 8.1

# Here, we need to be phpunit/phpunit=^7.5 installed even for PHP8 for which it is not compatible
before_install:
  - composer require "phpunit/phpunit=^7.5" "atk14/tester=^0.4" "atk14/string4=^0.4" "atk14/stop-watch=^0.1" --ignore-platform-reqs

script:
  - cd test && ../vendor/bin/run_unit_tests
