# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal

# Here, we need to be phpunit/phpunit=^7.5 installed even for PHP8 for which it is not compatible
before_install:
  - composer require "phpunit/phpunit=^7.5" "atk14/tester=^0.4" "atk14/string4=^0.4" "atk14/stop-watch=^0.1" --ignore-platform-reqs

script:
  - cd test && ../vendor/bin/run_unit_tests
